In [ ]:
# Column transformer

In [1]:
import pandas as pd
import numpy as np

In [2]:
df =pd.read_csv("covid_toy.csv")

In [3]:
df.head(3)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes
2   42   Male  101.0  Mild    Delhi        No

In [4]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=["has_covid"]),df["has_covid"],test_size=0.2)
#

In [7]:
X_train

    age  gender  fever   cough       city
56   71    Male    NaN  Strong    Kolkata
21   73    Male   98.0    Mild  Bangalore
72   83  Female  101.0    Mild    Kolkata
85   16  Female  103.0    Mild  Bangalore
18   64  Female   98.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
78   11    Male  100.0    Mild  Bangalore
48   66    Male   99.0  Strong  Bangalore
26   19  Female  100.0    Mild    Kolkata
93   27    Male  100.0    Mild    Kolkata
79   48  Female  103.0    Mild    Kolkata

[80 rows x 5 columns]

In [8]:
# by the use of column transformer

In [13]:
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder



transformer = ColumnTransformer(transformers=[
    ("tnf1",SimpleImputer(),["fever"]),
    ("tnf2",OrdinalEncoder(categories=[["Mild","Strong"]]),["cough"]),
    ("tnf3",OneHotEncoder(sparse_output=False,drop="first"),["gender","city"])
],remainder="passthrough")

In [14]:
transformer.fit_transform(X_train).shape

(80, 7)

In [16]:
transformer.transform(X_test).shape

(20, 7)

In [17]:
# manually type output

In [18]:
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[["fever"]])
X_test_fever = si.fit_transform(X_test[["fever"]])


X_train_fever.shape

(80, 1)

In [21]:
#     Ordinal encoding  ---cough

oe = OrdinalEncoder(categories=[["Mild","Strong"]])
X_train_cough = oe.fit_transform(X_train[["cough"]])
X_test_cough = oe.fit_transform(X_test[["cough"]])

X_train_cough.shape

(80, 1)

In [22]:
#one hot encoding
ohe =OneHotEncoder(drop="first",sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[["gender","city"]])
X_test_gender_city = ohe.fit_transform(X_test[["gender","city"]])

X_train_gender_city.shape

(80, 4)

In [23]:
# extracting age

X_train_age = X_train.drop(columns=["gender","fever","cough","city"]).values
X_test_age = X_test.drop(columns=["gender","fever","cough","city"]).values

X_train_age.shape

(80, 1)

In [24]:
x_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)

In [26]:
x_train_transformed.shape

(80, 7)