In [98]:
import numpy as np
import pandas as pd

In [99]:
df = pd.read_csv("placement.csv")

In [100]:
df.head()

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1

In [101]:
df.isnull().sum()

cgpa            0
resume_score    0
placed          0
dtype: int64

In [102]:
x= df.drop(columns =['placed'])

In [103]:
y= df['placed']

In [104]:
from sklearn.model_selection import train_test_split

In [105]:
x_train, y_train,x_test,y_test= train_test_split(x,y,test_size=0.2, random_state=42)

In [106]:
np.round(x_train.describe(),2)

        cgpa  resume_score
count  80.00         80.00
mean    6.95          7.00
std     1.13          1.01
min     5.27          4.95
25%     6.00          6.28
50%     6.62          7.15
75%     8.06          7.69
max     9.31          9.06

In [107]:
type(x_train)

pandas.core.frame.DataFrame

In [108]:
x_train.describe()

            cgpa  resume_score
count  80.000000     80.000000
mean    6.949625      6.999500
std     1.125988      1.010789
min     5.270000      4.950000
25%     5.997500      6.280000
50%     6.620000      7.155000
75%     8.062500      7.692500
max     9.310000      9.060000

In [109]:
from sklearn.preprocessing import StandardScaler

In [110]:
sc = StandardScaler()

In [111]:
x_train_sc =sc.fit_transform(x_train)    # fit means learn the parameters and transform means apply on that data

In [113]:

type(x_train_sc)

numpy.ndarray

In [114]:
x_train_new = pd.DataFrame(x_train_sc, columns = x_train.columns)
type(x_train_new)

pandas.core.frame.DataFrame

In [115]:
np.round(x_train_new.describe(),2)

        cgpa  resume_score
count  80.00         80.00
mean   -0.00         -0.00
std     1.01          1.01
min    -1.50         -2.04
25%    -0.85         -0.72
50%    -0.29          0.15
75%     0.99          0.69
max     2.11          2.05

In [116]:
# Normalisation

In [117]:
from sklearn.preprocessing import MinMaxScaler

In [118]:
mn = MinMaxScaler()

In [119]:
x_train_mn = mn.fit_transform(x_train)

In [120]:
x_train_mn_new = pd.DataFrame(x_train_mn, columns = x_train.columns)

In [121]:
np.round(x_train_mn_new.describe(),2)

        cgpa  resume_score
count  80.00         80.00
mean    0.42          0.50
std     0.28          0.25
min     0.00          0.00
25%     0.18          0.32
50%     0.33          0.54
75%     0.69          0.67
max     1.00          1.00

In [ ]:
# data2

In [31]:
import pandas as pd
import numpy as np

In [32]:
df = pd.read_csv("covid_toy.csv")

In [33]:
df.head(3)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes
2   42   Male  101.0  Mild    Delhi        No

In [34]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [35]:
from sklearn.impute import SimpleImputer

In [36]:
si = SimpleImputer()

In [37]:
df["fever"] = si.fit_transform(df[["fever"]])

In [38]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [39]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [40]:
df["has_covid"].value_counts()

has_covid
No     55
Yes    45
Name: count, dtype: int64

In [41]:
df["city"].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [42]:
df["gender"] = df["gender"].map({"Male":0,"Female":1})
df["cough"] = df["cough"].map({"Mild":0,"Strong":1})
df["city"] = df["city"].map({"Kolkata":0,"Banglore":1, "Delhi":2,"Mumbai":3})
df["has_covid"] = df["has_covid"].map({"Yes":0,"No":1})

In [43]:
df.head(4)

   age  gender  fever  cough  city  has_covid
0   60       0  103.0      0   0.0          1
1   27       0  100.0      0   2.0          0
2   42       0  101.0      0   2.0          1
3   31       1   98.0      0   0.0          1

In [44]:
x =df.drop(columns = ["has_covid"])
y= df["has_covid"]

In [45]:
from sklearn.model_selection import train_test_split

In [46]:
x_train, y_train, x_test, y_test = train_test_split(x,y,test_size=0.2, random_state=42)

In [49]:
np.round(x_train.describe(),2)

         age  gender   fever  cough   city
count  80.00   80.00   80.00  80.00  53.00
mean   42.91    0.59  100.98   0.40   1.40
std    24.47    0.50    1.93   0.49   1.29
min     5.00    0.00   98.00   0.00   0.00
25%    20.00    0.00  100.00   0.00   0.00
50%    42.00    1.00  101.00   0.00   2.00
75%    65.00    1.00  102.00   1.00   3.00
max    84.00    1.00  104.00   1.00   3.00

In [50]:
from sklearn.preprocessing import StandardScaler

In [51]:
sc = StandardScaler()

In [52]:
x_train_sc = sc.fit_transform(x_train)

In [53]:
x_train_new =pd.DataFrame(x_train_sc, columns = x_train.columns)

In [55]:
np.round(x_train_new.describe(),2)

         age  gender  fever  cough   city
count  80.00   80.00  80.00  80.00  53.00
mean   -0.00   -0.00  -0.00  -0.00   0.00
std     1.01    1.01   1.01   1.01   1.01
min    -1.56   -1.19  -1.56  -0.82  -1.09
25%    -0.94   -1.19  -0.51  -0.82  -1.09
50%    -0.04    0.84   0.01  -0.82   0.47
75%     0.91    0.84   0.53   1.22   1.25
max     1.69    0.84   1.57   1.22   1.25

In [56]:
#data3

In [69]:
df= pd.read_csv("tip.csv")

In [70]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [71]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [72]:
df["sex"].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [73]:
df["sex"] = df["sex"].map({"Male":0,"Female":1})

In [75]:
df["day"].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [76]:
df['day'] =df['day'].map({'Thur':0,'Fri':1,'Sat':2,'Sun':3})

In [77]:
df["smoker"].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [78]:
df["smoker"]=df["smoker"].map({"Yes":0,"No":1})

In [80]:
df["time"].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [81]:
df["time"]=df["time"].map({"Lunch":0,"Dinner":1})

In [82]:
x=df.drop(columns=["total_bill"])
y = df["total_bill"]

In [83]:
from sklearn.model_selection import train_test_split

In [84]:
x_train,y_train,x_test,y_test= train_test_split(x,y,test_size=0.2, random_state=42)

In [85]:
np.round(x_train.describe(),2)

          tip     sex  smoker     day    time    size
count  195.00  195.00  195.00  195.00  195.00  195.00
mean     3.09    0.35    0.62    1.74    0.73    2.57
std      1.43    0.48    0.49    1.14    0.45    0.94
min      1.00    0.00    0.00    0.00    0.00    1.00
25%      2.00    0.00    0.00    1.00    0.00    2.00
50%      3.00    0.00    1.00    2.00    1.00    2.00
75%      3.70    1.00    1.00    3.00    1.00    3.00
max     10.00    1.00    1.00    3.00    1.00    6.00

In [86]:
from sklearn.preprocessing import StandardScaler

In [87]:
sc = StandardScaler()

In [88]:
x_train_sc = sc.fit_transform(x_train)

In [89]:
x_train_new=pd.DataFrame(x_train_sc, columns = x_train.columns)

In [90]:
np.round(x_train_new.describe(),2)

          tip     sex  smoker     day    time    size
count  195.00  195.00  195.00  195.00  195.00  195.00
mean    -0.00    0.00   -0.00    0.00    0.00   -0.00
std      1.00    1.00    1.00    1.00    1.00    1.00
min     -1.46   -0.73   -1.26   -1.53   -1.64   -1.68
25%     -0.76   -0.73   -1.26   -0.65   -1.64   -0.61
50%     -0.06   -0.73    0.79    0.23    0.61   -0.61
75%      0.43    1.37    0.79    1.10    0.61    0.45
max      4.85    1.37    0.79    1.10    0.61    3.65