In [16]:
import pandas as pd
import numpy as np

In [17]:
# LABEL ENCODING

In [18]:
df = pd.read_csv("covid_toy.csv")

In [19]:
df.head(3)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes
2   42   Male  101.0  Mild    Delhi        No

In [20]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [21]:
from sklearn.impute import SimpleImputer

In [22]:
si = SimpleImputer()

In [23]:
df["fever"]= si.fit_transform(df[["fever"]])

In [24]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [25]:
df.head(3)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes
2   42   Male  101.0  Mild    Delhi        No

In [26]:
from sklearn.preprocessing import LabelEncoder

In [27]:
lb =LabelEncoder()

In [28]:
df['gender']= lb.fit_transform(df['gender'])
df['cough'] = lb.fit_transform(df['cough'])
df['city'] = lb.fit_transform(df['city'])
df['has_covid'] = lb.fit_transform(df['has_covid'])

In [29]:
df.sample(3)

    age  gender  fever  cough  city  has_covid
77    8       0  101.0      0     2          0
27   33       0  102.0      1     1          0
34   74       1  102.0      0     3          1

In [30]:
df.head(3)

   age  gender  fever  cough  city  has_covid
0   60       1  103.0      0     2          0
1   27       1  100.0      0     1          1
2   42       1  101.0      0     1          0

In [31]:
x = df.drop(columns=['has_covid'])
y = df['has_covid']

In [32]:
from sklearn.model_selection import train_test_split

In [33]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [34]:
from sklearn.preprocessing import StandardScaler

In [35]:
sc = StandardScaler()

In [36]:
x_train_sc = sc.fit_transform(x_train)

In [37]:
x_train_new= pd.DataFrame(x_train_sc,columns=x_train.columns)

In [38]:
np.round(x_train_new.describe(),2)

         age  gender  fever  cough   city
count  80.00   80.00  80.00  80.00  80.00
mean    0.00   -0.00  -0.00  -0.00  -0.00
std     1.01    1.01   1.01   1.01   1.01
min    -1.56   -0.82  -1.48  -0.80  -1.18
25%    -0.94   -0.82  -0.95  -0.80  -1.18
50%    -0.01   -0.82   0.03  -0.80  -0.27
75%     0.89    1.22   0.64   1.26   0.64
max     1.67    1.22   1.69   1.26   1.55

In [39]:
from sklearn.preprocessing import MinMaxScaler

In [40]:
mn = MinMaxScaler()

In [41]:
x_train_mn = mn.fit_transform(x_train)

In [42]:
x_train_mn_new = pd.DataFrame(x_train_mn,columns=x_train.columns)

In [43]:
np.round(x_train_mn_new.describe(),2)

         age  gender  fever  cough   city
count  80.00   80.00  80.00  80.00  80.00
mean    0.48    0.40   0.47   0.39   0.43
std     0.31    0.49   0.32   0.49   0.37
min     0.00    0.00   0.00   0.00   0.00
25%     0.19    0.00   0.17   0.00   0.00
50%     0.48    0.00   0.47   0.00   0.33
75%     0.76    1.00   0.67   1.00   0.67
max     1.00    1.00   1.00   1.00   1.00

In [44]:
df.sample(3)

    age  gender  fever  cough  city  has_covid
28   16       1  104.0      0     2          0
1    27       1  100.0      0     1          1
31   83       1  103.0      0     2          0

In [45]:
# Ordinal Encoder

In [66]:
df = pd.read_csv("covid_toy.csv")

In [67]:
df.head(3)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes
2   42   Male  101.0  Mild    Delhi        No

In [68]:
df = df.drop(columns=['age','fever'])

In [69]:
df.head(3)

  gender cough     city has_covid
0   Male  Mild  Kolkata        No
1   Male  Mild    Delhi       Yes
2   Male  Mild    Delhi        No

In [70]:
df.value_counts('city')

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [71]:
from sklearn.preprocessing import OrdinalEncoder

In [75]:
oe =OrdinalEncoder(categories = [['Male','Female'],
                                ['Mild','Strong'],
                                ['Kolkata','Bangalore','Delhi', 'Mumbai'],
                                ['Yes','No']])

In [76]:
oe_sc = oe.fit_transform(df)

In [77]:
new_df = pd.DataFrame(oe_sc,columns=df.columns)

In [78]:
new_df.head(3)

   gender  cough  city  has_covid
0     0.0    0.0   0.0        1.0
1     0.0    0.0   2.0        0.0
2     0.0    0.0   2.0        1.0

In [80]:
new_df = new_df.astype(int)
new_df.head(3)

   gender  cough  city  has_covid
0       0      0     0          1
1       0      0     2          0
2       0      0     2          1