In [1]:
#2. LogisticRegression

In [2]:
import numpy as np
import pandas as pd

In [3]:
df= pd.read_csv("/content/Social_Network_Ads - Social_Network_Ads.csv")

In [4]:
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
lb = LabelEncoder()

In [8]:
df['Gender']= lb.fit_transform(df['Gender'])

In [9]:
df.head(3)

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510       1   19            19000          0
1  15810944       1   35            20000          0
2  15668575       0   26            43000          0

In [10]:
df =df.drop(columns =[ 'User ID'])
df.head(3)

   Gender  Age  EstimatedSalary  Purchased
0       1   19            19000          0
1       1   35            20000          0
2       0   26            43000          0

In [11]:
x =df.drop(columns =['Purchased'])
y= df['Purchased']

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state =42)

In [15]:
from sklearn.linear_model import LogisticRegression

In [17]:
lr =LogisticRegression()

In [18]:
lr.fit(x_train,y_train)

LogisticRegression()

In [19]:
y_pred =lr.predict(x_test)

In [20]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [21]:
accuracy_score(y_test,y_pred)

0.8875

In [22]:
from sklearn.metrics import precision_score

In [23]:
precision_score(y_test,y_pred)                #true positive rate

0.9130434782608695

In [24]:
confusion_matrix(y_test,y_pred)

array([[50,  2],
       [ 7, 21]])

In [ ]:
# 50 - TP
#21 = TN
#2 - FP
#7 =FN